/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.progra2.pk;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;

/**
 *
 * @author USUARIO
 */
public class VentanaPokedex extends javax.swing.JFrame {
    
    BufferedImage buffer1 = null;
    Image imagen1=null;
    int contador=0;
    
    
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
    
    @Override
    public void paint(Graphics g){
       super.paintComponents(g);
       Graphics2D g2 =(Graphics2D) imagenPokemon.getGraphics();
       
       g2.drawImage(buffer1,0,0,imagenPokemon.getWidth(),imagenPokemon.getHeight(),null);
       
       
    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();
        
        this.getContentPane().setBackground(Color.pink);
        try {
               imagen1= ImageIO.read(new File("C:\\Users\\USUARIO\\Clase11\\Proyecto\\datos\\imagenes\\black-white.png.png"));
       
        } catch (IOException e) {
             System.out.println("Error al cargar imagen");
        }
         
        buffer1 = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(),imagenPokemon.getHeight());

    Graphics2D g2 = buffer1.createGraphics();
    
    dibujaElPokemonQueEstaEnLaPosicion(30);
  
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
        String JDBC_URL="jdbc:mysql://localhost:3306/pokedexx?zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=UTC";
        conexion = DriverManager.getConnection(JDBC_URL,"root","Estefani5768");
         estado=conexion.createStatement();
        } catch (Exception e){
            System.out.println("Hay error"+e.getMessage());
        }
    
    }
    
    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion) {
 int fila = posicion / 31;
int columna = posicion % 31;
Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
 g2.setColor(Color.green);      
 g2.fillRect(0,0,//pinta el fondo del jpanel negro
 imagenPokemon.getWidth(), imagenPokemon.getHeight()); 

     g2.drawImage(imagen1,0,//posicion x inicial
         0,// posicion inicial del jpanel
         imagenPokemon.getWidth(), //ancho del jpanel
         imagenPokemon.getHeight(),// alto de jpanel
         columna*96,// posicion inial y dentro de la imagen de todos los pokemones
        fila*96, //posicion inicial Y dentro de la imagen de todos los pokemon
         columna*96 + 96,// posicion final de x
         fila*96+96,// posicion final  y 
         
         null
     
         );
     
 repaint();


 

        } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPokemon = new javax.swing.JPanel();
        izq = new javax.swing.JButton();
        der = new javax.swing.JButton();
        nombrepokemon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        izq.setText("<=Izquierda");

        der.setText("Derecha=>");

        nombrepokemon.setText("Aqui va el nombre del pokemon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrepokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(izq)
                                .addGap(86, 86, 86)
                                .addComponent(der)))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(nombrepokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izq)
                    .addComponent(der))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
//  
          String cueri ="select * from pokemon where id="+(contador-1);
       dibujaElPokemonQueEstaEnLaPosicion(contador);  
        try {
            resultadoConsulta= estado.executeQuery(cueri);
             if (resultadoConsulta.next()){
                 nombrepokemon.setText(resultadoConsulta.getString(2));
 }else {
 nombrepokemon.setText("Ese chucho no figura en la pokedex");
}                   contador --;
 if (contador <= 0){
contador = 1;
        }

            
      } catch (Exception e) {
System.out.println("Hubo un erro en derecha"+e.getMessage());
        }
 
   
dibujaElPokemonQueEstaEnLaPosicion(contador);      
    }
    
    private void derActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
         String cuerito ="select * from pokemon where id="+(contador+1);
       dibujaElPokemonQueEstaEnLaPosicion(contador);  
        try {
            resultadoConsulta= estado.executeQuery(cuerito);
             if (resultadoConsulta.next()){
                 nombrepokemon.setText(resultadoConsulta.getString(2));
 }else {
 nombrepokemon.setText("Ese chucho no figura en la pokedex");
}
            
        } catch (Exception e) {
System.out.println("Hubo un erro en derecha"+e.getMessage());
        }
        contador ++;
 if(contador >649){
 contador=649;
    }}
    
    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
      
       int codigo = Integer.parseInt(txtid.getText());
          String cuerito ="select * from pokemon where id="+txtid.getText();
          
      dibujaElPokemonQueEstaEnLaPosicion(codigo);
        try {
            resultadoConsulta= estado.executeQuery(cuerito);
             if (resultadoConsulta.next()){
                 nombrepokemon.setText(resultadoConsulta.getString(2)+"\n Especie="+resultadoConsulta.getString("species"));
 }else {
 nombrepokemon.setText("Ese chucho no figura en la pokedex");
}
            
        } catch (Exception e) {
System.out.println("Hubo un erro en derecha"+e.getMessage());
        }
                   
    

        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton der;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JLabel nombrepokemon;
    // End of variables declaration//GEN-END:variables
}
